steps:
# Dep is produced from a private cloud-builders repo
- name: 'gcr.io/$PROJECT_ID/dep'
  args: ['ensure', '-v']
  env: ['PROJECT_ROOT=github.com/solo-io/supergloo']
  id: 'dep'

- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', 'supergloo', 'github.com/solo-io/supergloo/cmd']
  env:
    - 'PROJECT_ROOT=github.com/solo-io/supergloo'
    - 'GOPATH=/workspace/gopath'
  id: 'compile'

- name: gcr.io/cloud-builders/gcloud
  args:
    - kms
    - decrypt
    - --ciphertext-file=./gopath/src/github.com/solo-io/supergloo/ci/aws_credentials.enc
    - --plaintext-file=/workspace/aws_credentials
    - --location=global
    - --keyring=build
    - --key=build-key
  waitFor: ['dep']
  id: 'setup-aws-creds'

- name: 'gcr.io/$PROJECT_ID/e2e-ginkgo'
  entrypoint: 'git'
  args: ['clone', 'https://github.com/solo-io/gloo', '/workspace/gopath/src/github.com/solo-io/gloo']
  id: 'clone-gloo'

  # Dep is produced from a private cloud-builders repo
- name: 'gcr.io/$PROJECT_ID/dep'
  args: ['ensure', '-v']
  env: ['PROJECT_ROOT=github.com/solo-io/gloo']
  dir: './gopath/src/github.com/solo-io/gloo'
  waitFor: ['clone-gloo']
  id: 'dep-gloo'

- name: 'gcr.io/$PROJECT_ID/e2e-ginkgo'
  env:
    - 'PROJECT_ROOT=github.com/solo-io/supergloo'
    - 'GOPATH=/workspace/gopath'
    - 'AWS_SHARED_CREDENTIALS_FILE=/workspace/aws_credentials'
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster'
    - 'RUN_KUBE_TESTS=1'
  dir: './gopath/src/github.com/solo-io/supergloo'
  args: ['-r', '-failFast', '--skipPackage=github.com/solo-io/supergloo/test/e2e/install']
  waitFor: ['setup-aws-creds', 'dep-gloo']
  id: 'test'

timeout: 6600s
