// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/supergloo/api/v1/observability.proto

package v1 // import "github.com/solo-io/supergloo/pkg/api/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"
import _ "github.com/solo-io/supergloo/pkg/api/external/gloo/v1"

import bytes "bytes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// observability config for the mesh
type Observability struct {
	// mesh configuration for prometheus
	Prometheus           *Prometheus `protobuf:"bytes,1,opt,name=prometheus" json:"prometheus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Observability) Reset()         { *m = Observability{} }
func (m *Observability) String() string { return proto.CompactTextString(m) }
func (*Observability) ProtoMessage()    {}
func (*Observability) Descriptor() ([]byte, []int) {
	return fileDescriptor_observability_e71271233ba7499d, []int{0}
}
func (m *Observability) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Observability.Unmarshal(m, b)
}
func (m *Observability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Observability.Marshal(b, m, deterministic)
}
func (dst *Observability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Observability.Merge(dst, src)
}
func (m *Observability) XXX_Size() int {
	return xxx_messageInfo_Observability.Size(m)
}
func (m *Observability) XXX_DiscardUnknown() {
	xxx_messageInfo_Observability.DiscardUnknown(m)
}

var xxx_messageInfo_Observability proto.InternalMessageInfo

func (m *Observability) GetPrometheus() *Prometheus {
	if m != nil {
		return m.Prometheus
	}
	return nil
}

//
type Prometheus struct {
	// kubernetes only. if specified, pods with these labels in the namespace will be restarted by supergloo
	PodLabels map[string]string `protobuf:"bytes,2,rep,name=pod_labels,json=podLabels" json:"pod_labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// enable prometheus scraping for metrics of this mesh type
	EnableMetrics        bool     `protobuf:"varint,3,opt,name=enable_metrics,json=enableMetrics,proto3" json:"enable_metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prometheus) Reset()         { *m = Prometheus{} }
func (m *Prometheus) String() string { return proto.CompactTextString(m) }
func (*Prometheus) ProtoMessage()    {}
func (*Prometheus) Descriptor() ([]byte, []int) {
	return fileDescriptor_observability_e71271233ba7499d, []int{1}
}
func (m *Prometheus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prometheus.Unmarshal(m, b)
}
func (m *Prometheus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prometheus.Marshal(b, m, deterministic)
}
func (dst *Prometheus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prometheus.Merge(dst, src)
}
func (m *Prometheus) XXX_Size() int {
	return xxx_messageInfo_Prometheus.Size(m)
}
func (m *Prometheus) XXX_DiscardUnknown() {
	xxx_messageInfo_Prometheus.DiscardUnknown(m)
}

var xxx_messageInfo_Prometheus proto.InternalMessageInfo

func (m *Prometheus) GetPodLabels() map[string]string {
	if m != nil {
		return m.PodLabels
	}
	return nil
}

func (m *Prometheus) GetEnableMetrics() bool {
	if m != nil {
		return m.EnableMetrics
	}
	return false
}

func init() {
	proto.RegisterType((*Observability)(nil), "supergloo.solo.io.Observability")
	proto.RegisterType((*Prometheus)(nil), "supergloo.solo.io.Prometheus")
	proto.RegisterMapType((map[string]string)(nil), "supergloo.solo.io.Prometheus.PodLabelsEntry")
}
func (this *Observability) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Observability)
	if !ok {
		that2, ok := that.(Observability)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Prometheus.Equal(that1.Prometheus) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Prometheus) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Prometheus)
	if !ok {
		that2, ok := that.(Prometheus)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.PodLabels) != len(that1.PodLabels) {
		return false
	}
	for i := range this.PodLabels {
		if this.PodLabels[i] != that1.PodLabels[i] {
			return false
		}
	}
	if this.EnableMetrics != that1.EnableMetrics {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

func init() {
	proto.RegisterFile("github.com/solo-io/supergloo/api/v1/observability.proto", fileDescriptor_observability_e71271233ba7499d)
}

var fileDescriptor_observability_e71271233ba7499d = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4f, 0x32, 0x31,
	0x10, 0xc6, 0xb3, 0x90, 0xf7, 0xcd, 0x4b, 0x09, 0xe4, 0x75, 0xe5, 0xb0, 0xd9, 0x44, 0x42, 0x48,
	0x8c, 0x1c, 0xa0, 0x0d, 0x78, 0xd0, 0x18, 0xbd, 0x98, 0x78, 0xf2, 0x1f, 0xd9, 0xa3, 0x17, 0xd2,
	0x42, 0x29, 0x0d, 0x85, 0x69, 0xda, 0xee, 0x2a, 0xdf, 0xc8, 0x4f, 0xe1, 0x87, 0xf1, 0x93, 0x98,
	0xed, 0x02, 0x62, 0x54, 0x4e, 0x3b, 0x33, 0xcf, 0x6f, 0x66, 0xe7, 0x99, 0xa2, 0x33, 0x21, 0xdd,
	0x2c, 0x65, 0x78, 0x0c, 0x0b, 0x62, 0x41, 0x41, 0x4f, 0x02, 0xb1, 0xa9, 0xe6, 0x46, 0x28, 0x00,
	0x42, 0xb5, 0x24, 0x59, 0x9f, 0x00, 0xb3, 0xdc, 0x64, 0x94, 0x49, 0x25, 0xdd, 0x0a, 0x6b, 0x03,
	0x0e, 0xc2, 0x83, 0x2d, 0x85, 0xf3, 0x3e, 0x2c, 0x21, 0x6e, 0x08, 0x10, 0xe0, 0x55, 0x92, 0x47,
	0x05, 0x18, 0x37, 0x05, 0x80, 0x50, 0x9c, 0xf8, 0x8c, 0xa5, 0x53, 0x32, 0x49, 0x0d, 0x75, 0x12,
	0x96, 0xbf, 0xe9, 0xcf, 0x86, 0x6a, 0xcd, 0x8d, 0x5d, 0xeb, 0x87, 0x7e, 0x93, 0xac, 0x9f, 0x03,
	0x2f, 0xeb, 0xbf, 0xc7, 0xdd, 0x9f, 0xd6, 0xce, 0xbf, 0x73, 0xe9, 0x36, 0x5b, 0x1b, 0x3e, 0x2d,
	0xe8, 0xf6, 0x03, 0xaa, 0x3d, 0xee, 0x5a, 0x08, 0xaf, 0x10, 0xd2, 0x06, 0x16, 0xdc, 0xcd, 0x78,
	0x6a, 0xa3, 0xa0, 0x15, 0x74, 0xaa, 0x83, 0x23, 0xfc, 0xcd, 0x11, 0x1e, 0x6e, 0xa1, 0x64, 0xa7,
	0xa1, 0xfd, 0x16, 0x20, 0xf4, 0x29, 0x85, 0xb7, 0x08, 0x69, 0x98, 0x8c, 0x14, 0x65, 0x5c, 0xd9,
	0xa8, 0xd4, 0x2a, 0x77, 0xaa, 0x83, 0xee, 0xde, 0x69, 0x78, 0x08, 0x93, 0x3b, 0x8f, 0xdf, 0x2c,
	0x9d, 0x59, 0x25, 0x15, 0xbd, 0xc9, 0xc3, 0x63, 0x54, 0xe7, 0x4b, 0xca, 0x14, 0x1f, 0x2d, 0xb8,
	0x33, 0x72, 0x6c, 0xa3, 0x72, 0x2b, 0xe8, 0xfc, 0x4b, 0x6a, 0x45, 0xf5, 0xbe, 0x28, 0xc6, 0x97,
	0xa8, 0xfe, 0x75, 0x46, 0xf8, 0x1f, 0x95, 0xe7, 0x7c, 0xe5, 0xcd, 0x54, 0x92, 0x3c, 0x0c, 0x1b,
	0xe8, 0x4f, 0x46, 0x55, 0xca, 0xa3, 0x92, 0xaf, 0x15, 0xc9, 0x45, 0xe9, 0x3c, 0xb8, 0xee, 0xbd,
	0xbe, 0x37, 0x83, 0xa7, 0x93, 0xbd, 0x6f, 0xaf, 0xe7, 0x62, 0x7d, 0x49, 0xf6, 0xd7, 0x9f, 0xf1,
	0xf4, 0x23, 0x00, 0x00, 0xff, 0xff, 0xee, 0x33, 0x31, 0xb2, 0x2d, 0x02, 0x00, 0x00,
}
