// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/supergloo/api/v1/routing.proto

package v1 // import "github.com/solo-io/supergloo/pkg/api/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import types "github.com/gogo/protobuf/types"
import core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"
import v1 "github.com/solo-io/supergloo/pkg/api/external/gloo/v1"
import v1alpha3 "github.com/solo-io/supergloo/pkg/api/external/istio/networking/v1alpha3"

import bytes "bytes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// @solo-kit:resource.short_name=rr
// @solo-kit:resource.plural_name=routingrules
// @solo-kit:resource.resource_groups=translator.supergloo.solo.io
// rules to add features such as Fault Injection and Retries to a mesh
type RoutingRule struct {
	// Status indicates the validation status of this resource.
	// Status is read-only by clients, and set by gloo during validation
	Status core.Status `protobuf:"bytes,100,opt,name=status" json:"status" testdiff:"ignore"`
	// Metadata contains the object metadata for this resource
	Metadata core.Metadata `protobuf:"bytes,99,opt,name=metadata" json:"metadata"`
	// target where we apply this rule
	TargetMesh *core.ResourceRef `protobuf:"bytes,1,opt,name=target_mesh,json=targetMesh" json:"target_mesh,omitempty"`
	// source upstreams to apply the rule to. if empty, applies to all sources.
	Sources []*core.ResourceRef `protobuf:"bytes,2,rep,name=sources" json:"sources,omitempty"`
	// destination upstreams for which this rule applies. if empty, applies to all destinations
	Destinations []*core.ResourceRef `protobuf:"bytes,3,rep,name=destinations" json:"destinations,omitempty"`
	// if specified, this rule will only apply to http requests in the mesh matching these parameters
	RequestMatchers []*v1.Matcher `protobuf:"bytes,4,rep,name=request_matchers,json=requestMatchers" json:"request_matchers,omitempty"`
	// configuration to enable traffic shifting, e.g. by percentage or for alternate destinations
	TrafficShifting *TrafficShifting `protobuf:"bytes,5,opt,name=traffic_shifting,json=trafficShifting" json:"traffic_shifting,omitempty"`
	// configuration to enable fault injection for this rule
	FaultInjection *v1alpha3.HTTPFaultInjection `protobuf:"bytes,6,opt,name=fault_injection,json=faultInjection" json:"fault_injection,omitempty"`
	// Timeout for this rule
	Timeout *types.Duration `protobuf:"bytes,7,opt,name=timeout" json:"timeout,omitempty"`
	// Retry policy for for this rule
	Retries *v1alpha3.HTTPRetry `protobuf:"bytes,8,opt,name=retries" json:"retries,omitempty"`
	// Cross-Origin Resource Sharing policy (CORS) for this rule. Refer to
	// https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
	// for further details about cross origin resource sharing.
	CorsPolicy *v1alpha3.CorsPolicy `protobuf:"bytes,10,opt,name=cors_policy,json=corsPolicy" json:"cors_policy,omitempty"`
	// Mirror HTTP traffic to a another destination for this rule. Traffic will still be sent
	// to its original destination as normal.
	Mirror *v1.Destination `protobuf:"bytes,9,opt,name=mirror" json:"mirror,omitempty"`
	// manipulate request and response headers for this rule
	HeaderManipulaition  *HeaderManipulation `protobuf:"bytes,12,opt,name=header_manipulaition,json=headerManipulaition" json:"header_manipulaition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RoutingRule) Reset()         { *m = RoutingRule{} }
func (m *RoutingRule) String() string { return proto.CompactTextString(m) }
func (*RoutingRule) ProtoMessage()    {}
func (*RoutingRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_routing_12071c6470edee1e, []int{0}
}
func (m *RoutingRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutingRule.Unmarshal(m, b)
}
func (m *RoutingRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutingRule.Marshal(b, m, deterministic)
}
func (dst *RoutingRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutingRule.Merge(dst, src)
}
func (m *RoutingRule) XXX_Size() int {
	return xxx_messageInfo_RoutingRule.Size(m)
}
func (m *RoutingRule) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutingRule.DiscardUnknown(m)
}

var xxx_messageInfo_RoutingRule proto.InternalMessageInfo

func (m *RoutingRule) GetStatus() core.Status {
	if m != nil {
		return m.Status
	}
	return core.Status{}
}

func (m *RoutingRule) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func (m *RoutingRule) GetTargetMesh() *core.ResourceRef {
	if m != nil {
		return m.TargetMesh
	}
	return nil
}

func (m *RoutingRule) GetSources() []*core.ResourceRef {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *RoutingRule) GetDestinations() []*core.ResourceRef {
	if m != nil {
		return m.Destinations
	}
	return nil
}

func (m *RoutingRule) GetRequestMatchers() []*v1.Matcher {
	if m != nil {
		return m.RequestMatchers
	}
	return nil
}

func (m *RoutingRule) GetTrafficShifting() *TrafficShifting {
	if m != nil {
		return m.TrafficShifting
	}
	return nil
}

func (m *RoutingRule) GetFaultInjection() *v1alpha3.HTTPFaultInjection {
	if m != nil {
		return m.FaultInjection
	}
	return nil
}

func (m *RoutingRule) GetTimeout() *types.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func (m *RoutingRule) GetRetries() *v1alpha3.HTTPRetry {
	if m != nil {
		return m.Retries
	}
	return nil
}

func (m *RoutingRule) GetCorsPolicy() *v1alpha3.CorsPolicy {
	if m != nil {
		return m.CorsPolicy
	}
	return nil
}

func (m *RoutingRule) GetMirror() *v1.Destination {
	if m != nil {
		return m.Mirror
	}
	return nil
}

func (m *RoutingRule) GetHeaderManipulaition() *HeaderManipulation {
	if m != nil {
		return m.HeaderManipulaition
	}
	return nil
}

// enable traffic shifting for any http requests sent to one of the destinations on this rule
type TrafficShifting struct {
	// split traffic between these subsets based on their weights
	// weights should add to 100
	Destinations         []*WeightedDestination `protobuf:"bytes,1,rep,name=destinations" json:"destinations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TrafficShifting) Reset()         { *m = TrafficShifting{} }
func (m *TrafficShifting) String() string { return proto.CompactTextString(m) }
func (*TrafficShifting) ProtoMessage()    {}
func (*TrafficShifting) Descriptor() ([]byte, []int) {
	return fileDescriptor_routing_12071c6470edee1e, []int{1}
}
func (m *TrafficShifting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficShifting.Unmarshal(m, b)
}
func (m *TrafficShifting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficShifting.Marshal(b, m, deterministic)
}
func (dst *TrafficShifting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficShifting.Merge(dst, src)
}
func (m *TrafficShifting) XXX_Size() int {
	return xxx_messageInfo_TrafficShifting.Size(m)
}
func (m *TrafficShifting) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficShifting.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficShifting proto.InternalMessageInfo

func (m *TrafficShifting) GetDestinations() []*WeightedDestination {
	if m != nil {
		return m.Destinations
	}
	return nil
}

// WeightedDestination attaches a weight to a single destination.
type WeightedDestination struct {
	Upstream *core.ResourceRef `protobuf:"bytes,1,opt,name=upstream" json:"upstream,omitempty"`
	// Weight must be greater than zero
	// Routing to each destination will be balanced by the ratio of the destination's weight to the total weight on a route
	Weight               uint32   `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeightedDestination) Reset()         { *m = WeightedDestination{} }
func (m *WeightedDestination) String() string { return proto.CompactTextString(m) }
func (*WeightedDestination) ProtoMessage()    {}
func (*WeightedDestination) Descriptor() ([]byte, []int) {
	return fileDescriptor_routing_12071c6470edee1e, []int{2}
}
func (m *WeightedDestination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeightedDestination.Unmarshal(m, b)
}
func (m *WeightedDestination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeightedDestination.Marshal(b, m, deterministic)
}
func (dst *WeightedDestination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeightedDestination.Merge(dst, src)
}
func (m *WeightedDestination) XXX_Size() int {
	return xxx_messageInfo_WeightedDestination.Size(m)
}
func (m *WeightedDestination) XXX_DiscardUnknown() {
	xxx_messageInfo_WeightedDestination.DiscardUnknown(m)
}

var xxx_messageInfo_WeightedDestination proto.InternalMessageInfo

func (m *WeightedDestination) GetUpstream() *core.ResourceRef {
	if m != nil {
		return m.Upstream
	}
	return nil
}

func (m *WeightedDestination) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

// manipulate request and response headers
type HeaderManipulation struct {
	// HTTP headers to remove before returning a response to the caller.
	RemoveResponseHeaders []string `protobuf:"bytes,12,rep,name=remove_response_headers,json=removeResponseHeaders" json:"remove_response_headers,omitempty"`
	// Additional HTTP headers to add before returning a response to the
	// caller.
	AppendResponseHeaders map[string]string `protobuf:"bytes,13,rep,name=append_response_headers,json=appendResponseHeaders" json:"append_response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// HTTP headers to remove before forwarding a request to the
	// destination service.
	RemoveRequestHeaders []string `protobuf:"bytes,14,rep,name=remove_request_headers,json=removeRequestHeaders" json:"remove_request_headers,omitempty"`
	// Additional HTTP headers to add before forwarding a request to the
	// destination service.
	AppendRequestHeaders map[string]string `protobuf:"bytes,15,rep,name=append_request_headers,json=appendRequestHeaders" json:"append_request_headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HeaderManipulation) Reset()         { *m = HeaderManipulation{} }
func (m *HeaderManipulation) String() string { return proto.CompactTextString(m) }
func (*HeaderManipulation) ProtoMessage()    {}
func (*HeaderManipulation) Descriptor() ([]byte, []int) {
	return fileDescriptor_routing_12071c6470edee1e, []int{3}
}
func (m *HeaderManipulation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderManipulation.Unmarshal(m, b)
}
func (m *HeaderManipulation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderManipulation.Marshal(b, m, deterministic)
}
func (dst *HeaderManipulation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderManipulation.Merge(dst, src)
}
func (m *HeaderManipulation) XXX_Size() int {
	return xxx_messageInfo_HeaderManipulation.Size(m)
}
func (m *HeaderManipulation) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderManipulation.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderManipulation proto.InternalMessageInfo

func (m *HeaderManipulation) GetRemoveResponseHeaders() []string {
	if m != nil {
		return m.RemoveResponseHeaders
	}
	return nil
}

func (m *HeaderManipulation) GetAppendResponseHeaders() map[string]string {
	if m != nil {
		return m.AppendResponseHeaders
	}
	return nil
}

func (m *HeaderManipulation) GetRemoveRequestHeaders() []string {
	if m != nil {
		return m.RemoveRequestHeaders
	}
	return nil
}

func (m *HeaderManipulation) GetAppendRequestHeaders() map[string]string {
	if m != nil {
		return m.AppendRequestHeaders
	}
	return nil
}

// Percent specifies a percentage in the range of [0.0, 100.0].
type Percent struct {
	Value                float64  `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Percent) Reset()         { *m = Percent{} }
func (m *Percent) String() string { return proto.CompactTextString(m) }
func (*Percent) ProtoMessage()    {}
func (*Percent) Descriptor() ([]byte, []int) {
	return fileDescriptor_routing_12071c6470edee1e, []int{4}
}
func (m *Percent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Percent.Unmarshal(m, b)
}
func (m *Percent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Percent.Marshal(b, m, deterministic)
}
func (dst *Percent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Percent.Merge(dst, src)
}
func (m *Percent) XXX_Size() int {
	return xxx_messageInfo_Percent.Size(m)
}
func (m *Percent) XXX_DiscardUnknown() {
	xxx_messageInfo_Percent.DiscardUnknown(m)
}

var xxx_messageInfo_Percent proto.InternalMessageInfo

func (m *Percent) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*RoutingRule)(nil), "supergloo.solo.io.RoutingRule")
	proto.RegisterType((*TrafficShifting)(nil), "supergloo.solo.io.TrafficShifting")
	proto.RegisterType((*WeightedDestination)(nil), "supergloo.solo.io.WeightedDestination")
	proto.RegisterType((*HeaderManipulation)(nil), "supergloo.solo.io.HeaderManipulation")
	proto.RegisterMapType((map[string]string)(nil), "supergloo.solo.io.HeaderManipulation.AppendRequestHeadersEntry")
	proto.RegisterMapType((map[string]string)(nil), "supergloo.solo.io.HeaderManipulation.AppendResponseHeadersEntry")
	proto.RegisterType((*Percent)(nil), "supergloo.solo.io.Percent")
}
func (this *RoutingRule) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RoutingRule)
	if !ok {
		that2, ok := that.(RoutingRule)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !this.TargetMesh.Equal(that1.TargetMesh) {
		return false
	}
	if len(this.Sources) != len(that1.Sources) {
		return false
	}
	for i := range this.Sources {
		if !this.Sources[i].Equal(that1.Sources[i]) {
			return false
		}
	}
	if len(this.Destinations) != len(that1.Destinations) {
		return false
	}
	for i := range this.Destinations {
		if !this.Destinations[i].Equal(that1.Destinations[i]) {
			return false
		}
	}
	if len(this.RequestMatchers) != len(that1.RequestMatchers) {
		return false
	}
	for i := range this.RequestMatchers {
		if !this.RequestMatchers[i].Equal(that1.RequestMatchers[i]) {
			return false
		}
	}
	if !this.TrafficShifting.Equal(that1.TrafficShifting) {
		return false
	}
	if !this.FaultInjection.Equal(that1.FaultInjection) {
		return false
	}
	if !this.Timeout.Equal(that1.Timeout) {
		return false
	}
	if !this.Retries.Equal(that1.Retries) {
		return false
	}
	if !this.CorsPolicy.Equal(that1.CorsPolicy) {
		return false
	}
	if !this.Mirror.Equal(that1.Mirror) {
		return false
	}
	if !this.HeaderManipulaition.Equal(that1.HeaderManipulaition) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *TrafficShifting) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TrafficShifting)
	if !ok {
		that2, ok := that.(TrafficShifting)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Destinations) != len(that1.Destinations) {
		return false
	}
	for i := range this.Destinations {
		if !this.Destinations[i].Equal(that1.Destinations[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *WeightedDestination) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*WeightedDestination)
	if !ok {
		that2, ok := that.(WeightedDestination)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Upstream.Equal(that1.Upstream) {
		return false
	}
	if this.Weight != that1.Weight {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *HeaderManipulation) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HeaderManipulation)
	if !ok {
		that2, ok := that.(HeaderManipulation)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.RemoveResponseHeaders) != len(that1.RemoveResponseHeaders) {
		return false
	}
	for i := range this.RemoveResponseHeaders {
		if this.RemoveResponseHeaders[i] != that1.RemoveResponseHeaders[i] {
			return false
		}
	}
	if len(this.AppendResponseHeaders) != len(that1.AppendResponseHeaders) {
		return false
	}
	for i := range this.AppendResponseHeaders {
		if this.AppendResponseHeaders[i] != that1.AppendResponseHeaders[i] {
			return false
		}
	}
	if len(this.RemoveRequestHeaders) != len(that1.RemoveRequestHeaders) {
		return false
	}
	for i := range this.RemoveRequestHeaders {
		if this.RemoveRequestHeaders[i] != that1.RemoveRequestHeaders[i] {
			return false
		}
	}
	if len(this.AppendRequestHeaders) != len(that1.AppendRequestHeaders) {
		return false
	}
	for i := range this.AppendRequestHeaders {
		if this.AppendRequestHeaders[i] != that1.AppendRequestHeaders[i] {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Percent) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Percent)
	if !ok {
		that2, ok := that.(Percent)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

func init() {
	proto.RegisterFile("github.com/solo-io/supergloo/api/v1/routing.proto", fileDescriptor_routing_12071c6470edee1e)
}

var fileDescriptor_routing_12071c6470edee1e = []byte{
	// 851 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x4e, 0xdc, 0x46,
	0x14, 0xee, 0x02, 0x59, 0x60, 0x20, 0x59, 0x32, 0x2c, 0xc4, 0xec, 0x05, 0x20, 0x4b, 0x6d, 0xb8,
	0x68, 0x6c, 0x6d, 0x69, 0x2b, 0x84, 0x54, 0x95, 0xd2, 0xb4, 0xa1, 0x95, 0x56, 0x42, 0x13, 0xa4,
	0x56, 0x95, 0x2a, 0x6b, 0xb0, 0x8f, 0xed, 0x29, 0xb6, 0xc7, 0x9d, 0x9f, 0x25, 0xbc, 0x40, 0x9f,
	0xa5, 0x8f, 0xd2, 0xa7, 0x88, 0xd4, 0x3e, 0x42, 0x9f, 0x20, 0xf2, 0x78, 0xbc, 0xac, 0x61, 0x37,
	0x21, 0x57, 0xeb, 0xf1, 0xf7, 0x33, 0xdf, 0x9c, 0x73, 0x66, 0x8d, 0x86, 0x09, 0x53, 0xa9, 0xbe,
	0xf4, 0x42, 0x9e, 0xfb, 0x92, 0x67, 0xfc, 0x05, 0xe3, 0xbe, 0xd4, 0x25, 0x88, 0x24, 0xe3, 0xdc,
	0xa7, 0x25, 0xf3, 0xc7, 0x43, 0x5f, 0x70, 0xad, 0x58, 0x91, 0x78, 0xa5, 0xe0, 0x8a, 0xe3, 0xa7,
	0x13, 0xdc, 0xab, 0x14, 0x1e, 0xe3, 0x83, 0x7e, 0xc2, 0x13, 0x6e, 0x50, 0xbf, 0x7a, 0xaa, 0x89,
	0x83, 0xdd, 0x84, 0xf3, 0x24, 0x03, 0xdf, 0xac, 0x2e, 0x75, 0xec, 0x47, 0x5a, 0x50, 0xc5, 0x78,
	0x31, 0x0f, 0xbf, 0x16, 0xb4, 0x2c, 0x41, 0x48, 0x8b, 0x6f, 0x9a, 0x0c, 0xe3, 0x61, 0x45, 0x78,
	0x73, 0x63, 0x5f, 0xfa, 0x4c, 0x2a, 0xc6, 0xfd, 0x02, 0xd4, 0x35, 0x17, 0x57, 0xac, 0x48, 0xfc,
	0xf1, 0x90, 0x66, 0x65, 0x4a, 0x0f, 0xfd, 0x31, 0x13, 0x4a, 0xd3, 0x2c, 0x90, 0x20, 0xc6, 0x2c,
	0x04, 0x2b, 0x98, 0x79, 0xc2, 0xea, 0xf7, 0x8a, 0xa9, 0xe6, 0x80, 0x39, 0x28, 0x1a, 0x51, 0x45,
	0x9b, 0x3d, 0x1e, 0x20, 0x91, 0x8a, 0x2a, 0xdd, 0x24, 0xfd, 0xfc, 0x01, 0x02, 0x01, 0x71, 0xcd,
	0x76, 0xff, 0xed, 0xa2, 0x35, 0x52, 0x97, 0x94, 0xe8, 0x0c, 0xf0, 0x2b, 0xd4, 0xad, 0xdd, 0x9c,
	0x68, 0xbf, 0x73, 0xb0, 0xf6, 0x45, 0xdf, 0x0b, 0xb9, 0x80, 0xa6, 0xb8, 0xde, 0x6b, 0x83, 0x9d,
	0xee, 0xfc, 0xf3, 0x76, 0xef, 0x93, 0xff, 0xdf, 0xee, 0x3d, 0x55, 0x20, 0x55, 0xc4, 0xe2, 0xf8,
	0xd8, 0x65, 0x49, 0xc1, 0x05, 0xb8, 0xc4, 0xca, 0xf1, 0x11, 0x5a, 0x69, 0x4e, 0xe2, 0x84, 0xc6,
	0x6a, 0xbb, 0x6d, 0x35, 0xb2, 0xe8, 0xe9, 0x52, 0x65, 0x46, 0x26, 0x6c, 0x7c, 0x8c, 0xd6, 0x14,
	0x15, 0x09, 0xa8, 0x20, 0x07, 0x99, 0x3a, 0x1d, 0x23, 0xde, 0x69, 0x8b, 0x09, 0x48, 0xae, 0x45,
	0x08, 0x04, 0x62, 0x82, 0x6a, 0xf6, 0x08, 0x64, 0x8a, 0x0f, 0xd1, 0x72, 0x0d, 0x48, 0x67, 0x61,
	0x7f, 0xf1, 0xfd, 0xba, 0x86, 0x89, 0xbf, 0x41, 0xeb, 0x11, 0x48, 0xc5, 0x0a, 0x33, 0x10, 0xd2,
	0x59, 0xfc, 0x90, 0xb2, 0x45, 0xc7, 0x27, 0x68, 0x43, 0xc0, 0x9f, 0x1a, 0xa4, 0x0a, 0x72, 0xaa,
	0xc2, 0x14, 0x84, 0x74, 0x96, 0x8c, 0xc5, 0x96, 0x37, 0x3d, 0x99, 0xde, 0xa8, 0x46, 0x49, 0xcf,
	0xd2, 0xed, 0x5a, 0xe2, 0x11, 0xda, 0x50, 0x82, 0xc6, 0x31, 0x0b, 0x03, 0x99, 0xb2, 0xb8, 0x6a,
	0x86, 0xf3, 0xc8, 0x1c, 0xdb, 0xf5, 0xee, 0x0d, 0xb8, 0x77, 0x51, 0x53, 0x5f, 0x5b, 0x26, 0xe9,
	0xa9, 0xf6, 0x0b, 0x7c, 0x8e, 0x7a, 0x31, 0xd5, 0x99, 0x0a, 0x58, 0xf1, 0x07, 0x84, 0x55, 0x48,
	0xa7, 0x6b, 0xdc, 0x9e, 0x7b, 0xb7, 0xa3, 0xea, 0x99, 0xd9, 0xad, 0xfc, 0xce, 0x2e, 0x2e, 0xce,
	0x7f, 0xac, 0xf8, 0x3f, 0x35, 0x74, 0xf2, 0x24, 0x6e, 0xad, 0xab, 0xb2, 0x2a, 0x96, 0x03, 0xd7,
	0xca, 0x59, 0xb6, 0xed, 0xa8, 0xef, 0x8b, 0xd7, 0xdc, 0x17, 0xef, 0xa5, 0xbd, 0x4f, 0xa4, 0x61,
	0xe2, 0x23, 0xb4, 0x2c, 0x40, 0x09, 0x06, 0xd2, 0x59, 0x31, 0xa2, 0xdd, 0xb9, 0xdb, 0x13, 0x50,
	0xe2, 0x86, 0x34, 0x74, 0x7c, 0x82, 0xd6, 0x42, 0x2e, 0x64, 0x50, 0xf2, 0x8c, 0x85, 0x37, 0x0e,
	0x32, 0xea, 0xbd, 0x99, 0xea, 0xef, 0xb9, 0x90, 0xe7, 0x86, 0x46, 0x50, 0x38, 0x79, 0xc6, 0x43,
	0xd4, 0xcd, 0x99, 0x10, 0x5c, 0x38, 0xab, 0x4d, 0xde, 0xe9, 0x12, 0xbe, 0xbc, 0xed, 0x1f, 0xb1,
	0x44, 0xfc, 0x2b, 0xea, 0xa7, 0x40, 0x23, 0x10, 0x41, 0x4e, 0x0b, 0x56, 0xea, 0x8c, 0x32, 0x53,
	0xba, 0x75, 0x63, 0xf0, 0xe9, 0x8c, 0x46, 0x9c, 0x19, 0xfa, 0xc8, 0xb2, 0x8d, 0xd9, 0x66, 0xda,
	0x7a, 0x67, 0x1c, 0xdc, 0xdf, 0x51, 0xef, 0x4e, 0xcf, 0xf0, 0xcf, 0x77, 0x46, 0xae, 0x63, 0xe6,
	0xe5, 0xb3, 0x19, 0x9b, 0xfc, 0x02, 0x2c, 0x49, 0x15, 0x44, 0xd3, 0x91, 0x5b, 0x5a, 0x37, 0x42,
	0x9b, 0x33, 0x48, 0xf8, 0x2b, 0xb4, 0xa2, 0x4b, 0xa9, 0x04, 0xd0, 0xfc, 0xc3, 0x77, 0x68, 0x42,
	0xc5, 0xdb, 0xa8, 0x7b, 0x6d, 0xdc, 0x9c, 0x85, 0xfd, 0xce, 0xc1, 0x63, 0x62, 0x57, 0xee, 0x5f,
	0x4b, 0x08, 0xdf, 0x3f, 0x30, 0xfe, 0x1a, 0x3d, 0x13, 0x90, 0xf3, 0x31, 0x04, 0x02, 0x64, 0xc9,
	0x0b, 0x09, 0x41, 0x5d, 0x02, 0xe9, 0xac, 0xef, 0x2f, 0x1e, 0xac, 0x92, 0xad, 0x1a, 0x26, 0x16,
	0xad, 0x2d, 0x24, 0x7e, 0x83, 0x9e, 0x55, 0xff, 0xaf, 0x45, 0x74, 0x5f, 0xf7, 0xd8, 0xd4, 0xe2,
	0xe4, 0x41, 0x05, 0xf7, 0xbe, 0x33, 0x26, 0x77, 0xdc, 0x7f, 0x28, 0xaa, 0x71, 0xda, 0xa2, 0xb3,
	0x30, 0xfc, 0x25, 0xda, 0x9e, 0x24, 0xae, 0x6f, 0x6d, 0xb3, 0xf1, 0x13, 0x13, 0xb8, 0xdf, 0x04,
	0x36, 0x60, 0xa3, 0xd2, 0x68, 0x7b, 0x92, 0xb7, 0xad, 0xea, 0x99, 0xb8, 0xdf, 0x7e, 0x5c, 0xdc,
	0x69, 0xef, 0x3a, 0x6d, 0x9f, 0xce, 0x80, 0x06, 0x67, 0x68, 0x30, 0xff, 0x84, 0x78, 0x03, 0x2d,
	0x5e, 0xc1, 0x8d, 0xe9, 0xee, 0x2a, 0xa9, 0x1e, 0x71, 0x1f, 0x3d, 0x1a, 0xd3, 0x4c, 0x83, 0x69,
	0xde, 0x2a, 0xa9, 0x17, 0xc7, 0x0b, 0x47, 0x9d, 0xc1, 0x2b, 0xb4, 0x33, 0x77, 0xf3, 0x8f, 0x31,
	0x72, 0xf7, 0xd0, 0xf2, 0x39, 0x88, 0x10, 0x0a, 0x75, 0x4b, 0xaa, 0x84, 0x1d, 0x4b, 0x3a, 0x7d,
	0xf1, 0xf7, 0x7f, 0xbb, 0x9d, 0xdf, 0x9e, 0xbf, 0xf7, 0x63, 0x5e, 0x5e, 0x25, 0xf6, 0x5b, 0x74,
	0xd9, 0x35, 0x7f, 0x21, 0x87, 0xef, 0x02, 0x00, 0x00, 0xff, 0xff, 0x30, 0xa1, 0x9a, 0x53, 0xfe,
	0x07, 0x00, 0x00,
}
